[buildPlans.iosevka-ccw1]
family = "Iosevka ccw1"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-ccw1.variants]
  inherits = "ss04"

    [buildPlans.iosevka-ccw1.variants.design]
    capital-q = "vertical-crossing"
    i = "hooky"
    j = "flat-hook-serifed"
    l = "hooky"
    t = "flat-hook"
    one = "no-base-long-top-serif"
    seven = "straight-serifless-crossbar"

[buildPlans.iosevka-ccw1.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-ccw1.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-ccw1.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ccw1.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
