[buildPlans.iosevka-ccw2]
family = "Iosevka ccw2"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-ccw2.variants]
  inherits = "ss05"

    [buildPlans.iosevka-ccw2.variants.design]
    g = "single-storey-flat-hook-earless-corner"
    l = "zshaped"
    zero = "tall-slashed"
    one = "no-base"

[buildPlans.iosevka-ccw2.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-ccw2.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-ccw2.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ccw2.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
